@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDIwNjkwMzZ9.C2b-mh_aDcF51htJURGOCxp8NoTHEp3SDnKcp3MGoZ8


### ao logar, gera um token que deve ser usado para acessar as rotas da API
curl    -X 'POST' 'http://127.0.0.1:8000/token' \
        -H 'accept: application/json' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -d 'username=abc&password=bolinhas'

### teste token
curl    -X 'GET' 'http://127.0.0.1:8000/token/logado/' \
        -H 'accept: application/json' \
        -H 'Authorization: Bearer {{token}}'