@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDIwNjkwMzZ9.C2b-mh_aDcF51htJURGOCxp8NoTHEp3SDnKcp3MGoZ8


### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{

    "nome": "Produto Exemplo",
    "foto": "iVBORw0KGgoAAAANSUhEUgAA...",
    "valor_unitario": 99.99
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
"nome" : "Produto",
"foto" : "1",
"valor_unitario" : 22.90,
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1
Authorization: Bearer {{token}}